### PR TITLE
Fix Synthetics delete_test parameter name

### PR DESCRIPTION
**Pull request by jonathan-hosmer**
Change doc string and error message to use the correct name for the `public_ids` parameter of `delete_test`.

### What does this PR do?
Correct an error message to use the proper name of a parameter.

### Description of the Change
Change doc string and error message to use the correct name for the `public_ids` parameter of `delete_test`.

### Alternate Designs
N/A

### Possible Drawbacks
N/A

### Verification Process
Run code using incorrect type for parameter to ensure error message displays correctly.

### Additional Notes
Also updated documentation here: https://github.com/DataDog/documentation/pull/8640

### Release Notes
Fix `Synthetics` `delete_test` parameter name in docstring and `ApiError` text.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/datadogpy/blob/master/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Comment by nmuesch** [comment]
Thanks @jonathan-hosmer This looks good to me, mind just updating the PR title to reflect what this fixes (it'll get used in the changelog when we release)

**Comment by jonathan-hosmer** [comment]
Updated.

**Review by jirikuncar — APPROVED** [review]

**Review by therve — APPROVED** [review]

**Pull request merged**
