### PR TITLE
[dogwrap] add priority option

### LINKED ISSUE #18: dogwrap events should determine priority based on result
<a href="https://github.com/miketheman"></img></a> **Issue by [miketheman](https://github.com/miketheman)**
_Wednesday Dec 18, 2013 at 13:07 GMT_
_Originally opened as https://github.com/DataDog/dogapi/issues/71_

----

Currently success and failure both come in as normal (default).
dogwrap command should both auto-select the correct one based on output, as well as allow operator to override with commandline flag.

### PR DESCRIPTION
**Pull request by yannmh**
Fix #18

I don' feel confortable about auto-selecting a priority based on the output (i.e. `SUCCESS` -> `low` and `ERROR` -> 'normal'.)
cc @miketheman

### CODE REVIEW

**Comment by miketheman** [comment]
@yannmh Thanks - I think this covers the operator-set priority just fine.

What I don't get with this is that there's still no method for a cron job failing to be the "right" priority.

An [example from our Chef handler](https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L104-L111) where we detect whether it was pass/fail, and set priority accordingly.

If I were to add dogwrap to any cron job (to emit events on completion), I'd want the successes to be quiet, and the failures to be visible.

I'm happy to explain this further - but what's making you uncomfortable with auto-detecting priority?

**Comment by yannmh** [comment]
Thanks for your reply.

I brought some extra changes in my PR. 

The reason for my concern is that this will change the event priorities of current jobs sumitting 'success'  type events, without any more notice than the CHANGELOG: can that be considered as a backward incompatibility ?

**Comment by yannmh** [comment]
I don't think it's an issue. Merging.

**Comment by miketheman** [comment]
Thanks!

**Pull request merged**
