### PR TITLE
Replace nose by pytest

### PR DESCRIPTION
**Pull request by jd**
Nose is not maintained for a few years now; it's not a really good idea to
stick to it at this point.

Uses pytest instead to run tests.

### CODE REVIEW

**Comment by jd** [comment]
I did not find how to run integrations test. Any hint?

**Comment by dabcoder** [comment]
Sorry for the delay, thanks for working on this.

> I did not find how to run integrations test. Any hint?

Should be with `python setup.py test` I think. Additional context: https://github.com/DataDog/datadogpy/pull/407.

**Comment by jd** [comment]
> Should be with python setup.py test I think.

Alright, I thought they should run with Travis but I see in #407 it's not the case (yet).

I've updated the PR to fix a `mark` issue and a few other things. It should work now. Anyone that knows how to run this  with an API key can double check :)

**Comment by jd** [comment]
Rebased.

**Comment by zippolyte** [comment]
Thanks, merging !

**Pull request merged**
