### PR TITLE
add support for coroutine functions

### PR DESCRIPTION
**Pull request by thehesiod**
Without this change only the time it takes to create the coroutine is reported.

### CODE REVIEW

**Comment by thehesiod** [comment]
I tried making the travis-ci tests to pass however the py2.x tests are looking at the await even when it isn't supposed to be included in that version.

**Comment by yannmh** [comment]
Sorry for the late answer @thehesiod!

Your changes look great. I am going to take a pass on it this week, and plan for a release next week. 

Thanks!

**Comment by thehesiod** [comment]
any updates?

**Comment by yannmh** [comment]
Thanks for your patience @thehesiod. 🙇 

Your changes look good to me. I rebased your PR on top of the latest changes, and made some small adjustments in the organization of the different methods 🔀 .

I opened a new PR with more details: https://github.com/DataDog/datadogpy/pull/159. Let's close this PR in the meantime.

**Pull request closed without merging**
